USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA SALES_DATA;

SELECT
    p.PRODUCT_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS f
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC;

SELECT
    p.CATEGORY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS f
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_SALES DESC;

SELECT
    ORDER_DATE,
    SUM(TOTAL_AMOUNT) AS DAILY_SALES
FROM FACT_ORDERS
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;

SELECT
    REGION,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;

SELECT
    REGION,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;

SELECT * FROM DIM_PRODUCT;
SELECT * FROM DIM_REGION;

SELECT 
    f.ORDER_ID, 
    f.PRODUCT_ID, 
    p.PRODUCT_NAME, 
    f.REGION, 
    f.TOTAL_AMOUNT
FROM FACT_ORDERS f
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
LIMIT 10;

SELECT 
    f.ORDER_ID, 
    f.REGION, 
    r.REGION AS REGION_NAME
FROM FACT_ORDERS f
JOIN DIM_REGION r ON f.REGION = r.REGION
LIMIT 10;

SELECT PRODUCT_ID, COUNT(*) FROM DIM_PRODUCT GROUP BY PRODUCT_ID HAVING COUNT(*) > 0;

SELECT REGION, COUNT(*) FROM DIM_REGION GROUP BY REGION HAVING COUNT(*) > 0;

-- From fact table
SELECT DISTINCT PRODUCT_ID FROM FACT_ORDERS ORDER BY PRODUCT_ID;
SELECT DISTINCT REGION FROM FACT_ORDERS ORDER BY REGION;

-- From dimension tables
SELECT DISTINCT PRODUCT_ID FROM DIM_PRODUCT ORDER BY PRODUCT_ID;
SELECT DISTINCT REGION FROM DIM_REGION ORDER BY REGION;

SELECT
    p.PRODUCT_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS f
JOIN DIM_PRODUCT p ON TRIM(UPPER(f.PRODUCT_ID)) = TRIM(UPPER(p.PRODUCT_ID))
GROUP BY p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC;

SELECT
    r.REGION,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS f
JOIN DIM_REGION r ON TRIM(UPPER(f.REGION)) = TRIM(UPPER(r.REGION))
GROUP BY r.REGION
ORDER BY TOTAL_SALES DESC;

SELECT
    f.PRODUCT_ID,
    p.PRODUCT_NAME,
    f.REGION,
    f.TOTAL_AMOUNT
FROM FACT_ORDERS f
LEFT JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
ORDER BY f.PRODUCT_ID;

SELECT
    p.PRODUCT_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS f
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC;

SELECT
    r.REGION,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS f
JOIN DIM_REGION r ON f.REGION = r.REGION
GROUP BY r.REGION
ORDER BY TOTAL_SALES DESC;

SELECT
    ORDER_DATE,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;

SELECT
    p.CATEGORY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_ORDERS f
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_SALES DESC;







